#!/usr/bin/perl -w

use strict;
use Error qw( :try );
use Unto::Essex::ServiceManager;
use Unto::Essex::UrlService;

my $USAGE = "purge_cache path/to/configuration.yml\n";

my $conf_file = $ARGV[0] or die $USAGE;

-f $conf_file or die $USAGE;

my $service_manager = new Unto::Essex::ServiceManager( $conf_file );

my $url_service = $service_manager->lookup( "url" ) or
   die( "Couldn't look up URL server" );

print "Begin purging URL cache\n";

$url_service->purge_cache( );

print "End purging URL cache\n";


$service_manager->release( $url_service );

$service_manager->dispose( );
